import "server-only";

import { createPdfBuilder, dateTime, humanize, money } from "@/lib/server/pdf-document";

import type { InventoryApiResponse } from "@/lib/catalog";

export type AppliedFilter = { label: string; value: string };

export type ListPdfMetadata = {
  generatedBy: string;
  appliedFilters: AppliedFilter[];
  /** Locations the actor is authorized to read, as shown on screen. */
  scope: string;
};

/** Shared preamble: what the copy is, who pulled it, when, and under which filters. */
function preamble(
  builder: Awaited<ReturnType<typeof createPdfBuilder>>,
  title: string,
  metadata: ListPdfMetadata,
  note: string,
) {
  builder.text(title, 22, true);
  builder.space(4);
  builder.text(`Generated: ${dateTime(new Date().toISOString())} (Asia/Manila)`);
  builder.text(`Generated by: ${metadata.generatedBy}`);
  builder.text(`Authorized scope: ${metadata.scope || "No authorized locations"}`);
  builder.text(note);
  builder.text(`Applied filters: ${metadata.appliedFilters.map((filter) => `${filter.label}: ${filter.value}`).join("; ") || "None"}`);
  builder.space(16);
}

export async function createInventoryListPdf(
  inventory: InventoryApiResponse,
  metadata: ListPdfMetadata,
): Promise<ArrayBuffer> {
  const builder = await createPdfBuilder({
    title: "Inventory List",
    documentTitle: "Predator Inventory List",
    generatedBy: metadata.generatedBy,
    footer: "Private | Authorized inventory scope | Times: Asia/Manila",
  });

  preamble(builder, "Inventory List", metadata,
    "Every row matching the applied filters, not only the page shown on screen. Available = on hand - reserved - quarantined.");

  builder.table("Inventory overview", [{ header: "Measure", width: 3 }, { header: "Total", width: 2, numeric: true }], [
    ["Rows exported", String(inventory.data.length)],
    ["Products in authorized scope", String(inventory.summary.totalProducts)],
    ["Units on hand in authorized scope", String(inventory.summary.totalUnits)],
    ["Products needing restock", String(inventory.summary.needsRestock)],
    [inventory.summary.incomingItemsLabel, String(inventory.summary.incomingItems)],
  ], true);

  const totals = inventory.data.reduce((sum, row) => ({
    onHand: sum.onHand + row.onHand,
    reserved: sum.reserved + row.reserved,
    quarantined: sum.quarantined + row.quarantined,
    available: sum.available + Math.max(row.onHand - row.reserved - row.quarantined, 0),
  }), { onHand: 0, reserved: 0, quarantined: 0, available: 0 });

  builder.table("Stock on record", [
    { header: "Item code", width: 1.3 }, { header: "Product", width: 3 }, { header: "Category", width: 1.3 },
    { header: "Location", width: 1.5 }, { header: "On hand", width: 0.9, numeric: true },
    { header: "Reserved", width: 0.9, numeric: true }, { header: "Quarantined", width: 1, numeric: true },
    { header: "Available", width: 0.9, numeric: true }, { header: "Reorder", width: 0.9, numeric: true },
    { header: "Status", width: 1.1 }, { header: "Last updated", width: 1.5 },
  ], [
    ...inventory.data.map((row) => [
      row.itemCode, row.name, row.category, row.location,
      String(row.onHand), String(row.reserved), String(row.quarantined),
      String(Math.max(row.onHand - row.reserved - row.quarantined, 0)), String(row.reorderLevel),
      row.status, dateTime(row.lastUpdated),
    ]),
    ["EXPORTED TOTAL", "", "", "", String(totals.onHand), String(totals.reserved), String(totals.quarantined), String(totals.available), "", "", ""],
  ], true);

  return builder.finish();
}

export type DirectSalesExportRow = {
  reference: string;
  manualReceiptNumber: string;
  postedAt: string;
  branch: string;
  customer: string;
  salesperson: string;
  encoder: string;
  paymentMethod: string;
  reviewStatus: string;
  units: number;
  discountAmount: number;
  totalAmount: number;
  amountPaid: number;
};

export async function createDirectSalesPdf(
  rows: DirectSalesExportRow[],
  metadata: ListPdfMetadata,
): Promise<ArrayBuffer> {
  const builder = await createPdfBuilder({
    title: "Direct Sales List",
    documentTitle: "Predator Direct Sales List",
    generatedBy: metadata.generatedBy,
    footer: "Private | Authorized sales scope | Times: Asia/Manila",
  });

  preamble(builder, "Direct Sales List", metadata,
    "Posted direct sales matching the applied filters, not only the page shown on screen. Amounts are recorded sale values, not collected cash.");

  const totals = rows.reduce((sum, row) => ({
    units: sum.units + row.units,
    discount: sum.discount + row.discountAmount,
    total: sum.total + row.totalAmount,
    paid: sum.paid + row.amountPaid,
  }), { units: 0, discount: 0, total: 0, paid: 0 });

  builder.table("Sales overview", [{ header: "Measure", width: 3 }, { header: "Total", width: 2, numeric: true }], [
    ["Sales exported", String(rows.length)],
    ["Units sold", String(totals.units)],
    ["Discounts", money(totals.discount)],
    ["Recorded sales", money(totals.total)],
    ["Amount paid on record", money(totals.paid)],
  ], true);

  builder.table("Posted direct sales", [
    { header: "Receipt / posted", width: 1.7 }, { header: "Reference", width: 1.3 },
    { header: "Branch", width: 1.3 }, { header: "Customer / personnel", width: 2.4 },
    { header: "Payment / review", width: 1.5 }, { header: "Units", width: 0.6, numeric: true },
    { header: "Discount", width: 1.2, numeric: true }, { header: "Total", width: 1.3, numeric: true },
    { header: "Paid", width: 1.3, numeric: true },
  ], [
    ...rows.map((row) => [
      `${row.manualReceiptNumber}\n${dateTime(row.postedAt)}`, row.reference, row.branch,
      `Customer: ${row.customer}\nSalesperson: ${row.salesperson}\nEncoder: ${row.encoder}`,
      `${humanize(row.paymentMethod)}\n${humanize(row.reviewStatus)}`,
      String(row.units), money(row.discountAmount), money(row.totalAmount), money(row.amountPaid),
    ]),
    ["EXPORTED TOTAL", "", "", "", "", String(totals.units), money(totals.discount), money(totals.total), money(totals.paid)],
  ], true);

  return builder.finish();
}

export type CustomerOrderExportRow = {
  orderNo: string;
  orderDate: string;
  releaseDate: string;
  branch: string;
  customer: string;
  salesperson: string;
  status: string;
  paymentStatus: string;
  itemSummary: string;
  totalItems: number;
  downpayment: number;
  totalAmount: number;
  balance: number;
};

export async function createCustomerOrdersPdf(
  rows: CustomerOrderExportRow[],
  metadata: ListPdfMetadata,
): Promise<ArrayBuffer> {
  const builder = await createPdfBuilder({
    title: "Customer Orders List",
    documentTitle: "Predator Customer Orders List",
    generatedBy: metadata.generatedBy,
    footer: "Private | Authorized customer order scope | Times: Asia/Manila",
  });

  preamble(builder, "Customer Orders List", metadata,
    "Customer orders matching the applied filters, not only the page shown on screen. Balance is the recorded order balance, not a collection record.");

  const totals = rows.reduce((sum, row) => ({
    items: sum.items + row.totalItems,
    downpayment: sum.downpayment + row.downpayment,
    total: sum.total + row.totalAmount,
    balance: sum.balance + row.balance,
  }), { items: 0, downpayment: 0, total: 0, balance: 0 });

  builder.table("Orders overview", [{ header: "Measure", width: 3 }, { header: "Total", width: 2, numeric: true }], [
    ["Orders exported", String(rows.length)],
    ["Items ordered", String(totals.items)],
    ["Downpayments on record", money(totals.downpayment)],
    ["Order amounts", money(totals.total)],
    ["Outstanding balance", money(totals.balance)],
  ], true);

  builder.table("Customer orders", [
    { header: "Order / dates", width: 1.8 }, { header: "Branch", width: 1.3 },
    { header: "Customer / salesperson", width: 2.2 }, { header: "Items", width: 2.6 },
    { header: "Status / payment", width: 1.5 }, { header: "Qty", width: 0.6, numeric: true },
    { header: "Downpayment", width: 1.3, numeric: true }, { header: "Total", width: 1.3, numeric: true },
    { header: "Balance", width: 1.3, numeric: true },
  ], [
    ...rows.map((row) => [
      `${row.orderNo}\nOrdered: ${row.orderDate}\nRelease: ${row.releaseDate}`, row.branch,
      `Customer: ${row.customer}\nSalesperson: ${row.salesperson}`, row.itemSummary,
      `${row.status}\n${row.paymentStatus}`, String(row.totalItems),
      money(row.downpayment), money(row.totalAmount), money(row.balance),
    ]),
    ["EXPORTED TOTAL", "", "", "", "", String(totals.items), money(totals.downpayment), money(totals.total), money(totals.balance)],
  ], true);

  return builder.finish();
}
