import "server-only";

import { createPdfBuilder, dateTime, humanize, money } from "@/lib/server/pdf-document";

import type { InventoryApiResponse } from "@/lib/catalog";

export type AppliedFilter = { label: string; value: string };

export type ListPdfMetadata = {
  generatedBy: string;
  appliedFilters: AppliedFilter[];
  /** Locations the actor is authorized to read, as shown on screen. */
  scope: string;
};

/** Shared preamble: what the copy is, who pulled it, when, and under which filters. */
function preamble(
  builder: Awaited<ReturnType<typeof createPdfBuilder>>,
  title: string,
  metadata: ListPdfMetadata,
  note: string,
) {
  builder.text(title, 22, true);
  builder.space(4);
  builder.text(`Generated: ${dateTime(new Date().toISOString())} (Asia/Manila)`);
  builder.text(`Generated by: ${metadata.generatedBy}`);
  builder.text(`Authorized scope: ${metadata.scope || "No authorized locations"}`);
  builder.text(note);
  builder.text(`Applied filters: ${metadata.appliedFilters.map((filter) => `${filter.label}: ${filter.value}`).join("; ") || "None"}`);
  builder.space(16);
}

export async function createInventoryListPdf(
  inventory: InventoryApiResponse,
  metadata: ListPdfMetadata,
): Promise<ArrayBuffer> {
  const builder = await createPdfBuilder({
    title: "Inventory List",
    documentTitle: "Predator Inventory List",
    generatedBy: metadata.generatedBy,
    footer: "Private | Authorized inventory scope | Times: Asia/Manila",
  });

  preamble(builder, "Inventory List", metadata,
    "Every row matching the applied filters, not only the page shown on screen. Available = on hand - reserved - quarantined.");

  builder.table("Inventory overview", [{ header: "Measure", width: 3 }, { header: "Total", width: 2, numeric: true }], [
    ["Rows exported", String(inventory.data.length)],
    ["Products in authorized scope", String(inventory.summary.totalProducts)],
    ["Units on hand in authorized scope", String(inventory.summary.totalUnits)],
    ["Products needing restock", String(inventory.summary.needsRestock)],
    [inventory.summary.incomingItemsLabel, String(inventory.summary.incomingItems)],
  ], true);

  /*
   * One line per product, laid out like the branch sheet this replaces: the
   * catalogue detail, then a column per branch holding what that branch can
   * sell, then the total and the price.
   *
   * The export used to print a line per branch balance, which repeated the
   * catalogue detail once for every branch and left the reader adding the
   * numbers up by hand. Reorder level and status are not printed: the sheet
   * does not carry them, and a printed page cannot be acted on the way the
   * screen can.
   */
  const products = new Map<string, typeof inventory.data>();
  for (const row of inventory.data) {
    products.set(row.itemCode, [...(products.get(row.itemCode) ?? []), row]);
  }

  const available = (row: (typeof inventory.data)[number]) =>
    Math.max(row.onHand - row.reserved - row.quarantined, 0);

  /*
   * Branch columns come from the rows themselves, so a renamed or added branch
   * shows up without touching this file. The sheet's own order is kept for the
   * five everyone knows; anything else follows alphabetically rather than
   * being dropped.
   */
  const SHEET_ORDER = ["QC", "BL", "LU", "VC", "SP"];
  const branchCodes = [...new Set(inventory.data.map((row) => row.locationCode).filter(Boolean))]
    .sort((left, right) => {
      const leftRank = SHEET_ORDER.indexOf(left);
      const rightRank = SHEET_ORDER.indexOf(right);
      if (leftRank !== -1 && rightRank !== -1) return leftRank - rightRank;
      if (leftRank !== -1) return -1;
      if (rightRank !== -1) return 1;
      return left.localeCompare(right);
    });

  const branchTotals = new Map(branchCodes.map((code) => [code, 0]));
  let exportedAvailable = 0;

  const productRows = [...products.values()].map((rows) => {
    const [first] = rows;
    const perBranch = new Map(branchCodes.map((code) => [code, 0]));
    for (const row of rows) {
      perBranch.set(row.locationCode, (perBranch.get(row.locationCode) ?? 0) + available(row));
    }
    const total = [...perBranch.values()].reduce((sum, value) => sum + value, 0);
    exportedAvailable += total;
    for (const code of branchCodes) {
      branchTotals.set(code, (branchTotals.get(code) ?? 0) + (perBranch.get(code) ?? 0));
    }

    return [
      first.itemCode,
      first.name,
      first.description || "",
      first.brand || "Unbranded",
      first.carModel || "Not set",
      first.yearModel || "Not set",
      ...branchCodes.map((code) => String(perBranch.get(code) ?? 0)),
      String(total),
      first.price === null ? "No price" : money(first.price),
    ];
  });

  builder.table("Stock on record", [
    { header: "Item Code", width: 0.9 }, { header: "Item Name", width: 1.8 },
    { header: "Description", width: 2.4 }, { header: "Brand", width: 1 },
    { header: "Car Model", width: 1.2 }, { header: "Year Model", width: 1.1 },
    ...branchCodes.map((code) => ({ header: code, width: 0.5, numeric: true })),
    { header: "Total Stock Available", width: 1.1, numeric: true },
    { header: "Price", width: 1.2, numeric: true },
  ], [
    ...productRows,
    [
      "EXPORTED TOTAL", "", "", "", "", "",
      ...branchCodes.map((code) => String(branchTotals.get(code) ?? 0)),
      String(exportedAvailable),
      "",
    ],
  ], true);

  return builder.finish();
}

export type DirectSalesExportRow = {
  reference: string;
  manualReceiptNumber: string;
  postedAt: string;
  branch: string;
  customer: string;
  salesperson: string;
  encoder: string;
  paymentMethod: string;
  reviewStatus: string;
  units: number;
  discountAmount: number;
  totalAmount: number;
  amountPaid: number;
};

export async function createDirectSalesPdf(
  rows: DirectSalesExportRow[],
  metadata: ListPdfMetadata,
): Promise<ArrayBuffer> {
  const builder = await createPdfBuilder({
    title: "Direct Sales List",
    documentTitle: "Predator Direct Sales List",
    generatedBy: metadata.generatedBy,
    footer: "Private | Authorized sales scope | Times: Asia/Manila",
  });

  preamble(builder, "Direct Sales List", metadata,
    "Posted direct sales matching the applied filters, not only the page shown on screen. Amounts are recorded sale values, not collected cash.");

  const totals = rows.reduce((sum, row) => ({
    units: sum.units + row.units,
    discount: sum.discount + row.discountAmount,
    total: sum.total + row.totalAmount,
    paid: sum.paid + row.amountPaid,
  }), { units: 0, discount: 0, total: 0, paid: 0 });

  builder.table("Sales overview", [{ header: "Measure", width: 3 }, { header: "Total", width: 2, numeric: true }], [
    ["Sales exported", String(rows.length)],
    ["Units sold", String(totals.units)],
    ["Discounts", money(totals.discount)],
    ["Recorded sales", money(totals.total)],
    ["Amount paid on record", money(totals.paid)],
  ], true);

  builder.table("Posted direct sales", [
    { header: "Receipt / posted", width: 1.7 }, { header: "Reference", width: 1.3 },
    { header: "Branch", width: 1.3 }, { header: "Customer / personnel", width: 2.4 },
    { header: "Payment / review", width: 1.5 }, { header: "Units", width: 0.6, numeric: true },
    { header: "Discount", width: 1.2, numeric: true }, { header: "Total", width: 1.3, numeric: true },
    { header: "Paid", width: 1.3, numeric: true },
  ], [
    ...rows.map((row) => [
      `${row.manualReceiptNumber}\n${dateTime(row.postedAt)}`, row.reference, row.branch,
      `Customer: ${row.customer}\nSalesperson: ${row.salesperson}\nEncoder: ${row.encoder}`,
      `${humanize(row.paymentMethod)}\n${humanize(row.reviewStatus)}`,
      String(row.units), money(row.discountAmount), money(row.totalAmount), money(row.amountPaid),
    ]),
    ["EXPORTED TOTAL", "", "", "", "", String(totals.units), money(totals.discount), money(totals.total), money(totals.paid)],
  ], true);

  return builder.finish();
}

export type CustomerOrderExportRow = {
  orderNo: string;
  orderDate: string;
  releaseDate: string;
  branch: string;
  customer: string;
  salesperson: string;
  status: string;
  paymentStatus: string;
  itemSummary: string;
  totalItems: number;
  downpayment: number;
  totalAmount: number;
  balance: number;
};

export async function createCustomerOrdersPdf(
  rows: CustomerOrderExportRow[],
  metadata: ListPdfMetadata,
): Promise<ArrayBuffer> {
  const builder = await createPdfBuilder({
    title: "Customer Orders List",
    documentTitle: "Predator Customer Orders List",
    generatedBy: metadata.generatedBy,
    footer: "Private | Authorized customer order scope | Times: Asia/Manila",
  });

  preamble(builder, "Customer Orders List", metadata,
    "Customer orders matching the applied filters, not only the page shown on screen. Balance is the recorded order balance, not a collection record.");

  const totals = rows.reduce((sum, row) => ({
    items: sum.items + row.totalItems,
    downpayment: sum.downpayment + row.downpayment,
    total: sum.total + row.totalAmount,
    balance: sum.balance + row.balance,
  }), { items: 0, downpayment: 0, total: 0, balance: 0 });

  builder.table("Orders overview", [{ header: "Measure", width: 3 }, { header: "Total", width: 2, numeric: true }], [
    ["Orders exported", String(rows.length)],
    ["Items ordered", String(totals.items)],
    ["Downpayments on record", money(totals.downpayment)],
    ["Order amounts", money(totals.total)],
    ["Outstanding balance", money(totals.balance)],
  ], true);

  builder.table("Customer orders", [
    { header: "Order / dates", width: 1.8 }, { header: "Branch", width: 1.3 },
    { header: "Customer / salesperson", width: 2.2 }, { header: "Items", width: 2.6 },
    { header: "Status / payment", width: 1.5 }, { header: "Qty", width: 0.6, numeric: true },
    { header: "Downpayment", width: 1.3, numeric: true }, { header: "Total", width: 1.3, numeric: true },
    { header: "Balance", width: 1.3, numeric: true },
  ], [
    ...rows.map((row) => [
      `${row.orderNo}\nOrdered: ${row.orderDate}\nRelease: ${row.releaseDate}`, row.branch,
      `Customer: ${row.customer}\nSalesperson: ${row.salesperson}`, row.itemSummary,
      `${row.status}\n${row.paymentStatus}`, String(row.totalItems),
      money(row.downpayment), money(row.totalAmount), money(row.balance),
    ]),
    ["EXPORTED TOTAL", "", "", "", "", String(totals.items), money(totals.downpayment), money(totals.total), money(totals.balance)],
  ], true);

  return builder.finish();
}
