import "server-only";

import { createPdfBuilder, dateTime, humanize, money, type PdfColumn } from "@/lib/server/pdf-document";

import type { ReportResult, SalesReport } from "@/lib/contracts/reports";

export async function createReportPdf(report: ReportResult, metadata: { generatedBy: string }): Promise<ArrayBuffer> {
  const TITLES: Record<ReportResult["type"], string> = {
    sales: "Sales Report",
    "salesperson-sales": "Sales by Salesperson",
    "inventory-summary": "Inventory Summary",
    "stock-movement": "Stock Movement",
    "returns-warranty": "Returns & Warranty",
  };
  const title = TITLES[report.type];
  const { text, table, space, finish } = await createPdfBuilder({
    title,
    documentTitle: `Chezcar ${title}`,
    generatedBy: metadata.generatedBy,
    footer: "Private | Authorized report scope | Times: Asia/Manila",
  });

  text(title, 22, true);
  space(4);
  text(`Generated: ${dateTime(report.generatedAt)} (Asia/Manila)`);
  text(`Generated by: ${metadata.generatedBy}`);
  text(`Authorized scope: ${report.effectiveScope.map((row) => row.label).join(", ") || "No authorized locations"}`);
  text(report.type === "inventory-summary"
    ? "Current branch snapshot. Available = on hand - reserved - quarantined. Positive available stock only; Stock Room and in-transit stock excluded. Comparison cells with no positive stock show 0."
    : `From ${report.dateFrom} to ${report.dateTo}, inclusive. Based on ${
        report.type === "sales" || report.type === "salesperson-sales"
          ? report.dateBasis === "VERIFIED_DATE" ? "verification" : "sale"
          : report.type === "stock-movement" ? "sale" : "case creation"
      } date in Asia/Manila.`);
  text(`Applied filters: ${report.appliedFilters.map((filter) => `${filter.label}: ${filter.value}`).join("; ") || "None"}`);
  space(16);

  if (report.type === "sales" || report.type === "salesperson-sales") {
    const total = report.grandTotal;
    text(report.dateBasis === "VERIFIED_DATE"
      ? "Period measured on the date Accounting verified each receipt."
      : "Period measured on the date each receipt was issued, so this printout does not change as Accounting works through its queue.");
    // The printed copy states its own gap rather than quietly understating.
    if (report.pending.count > 0) {
      text(`Still unverified: ${report.pending.count} receipt(s) issued in this period worth ${money(report.pending.amount)}. They are excluded from every total below.`);
    }
    table("Sales overview", [{ header: "Measure", width: 3 }, { header: "Total", width: 2, numeric: true }], [
      ["Verified transactions", String(total.transactionCount)], ["Units sold", String(total.units)],
      ["Discounts", money(total.totalDiscount)], ["Average sale", money(total.averageSale)],
      ["Overall verified sales", money(total.totalAmount)],
    ], true);
    if (report.type === "salesperson-sales") {
      text("Verified sales attributed to each salesperson, not commissions or collected payments. Older unattributed sales remain under Not recorded (legacy).");
      table("Salesperson subtotals", [
        { header: "Salesperson", width: 3 }, { header: "Transactions", width: 1.1, numeric: true },
        { header: "Units", width: 0.8, numeric: true }, { header: "Discounts", width: 1.5, numeric: true },
        { header: "Average sale", width: 1.5, numeric: true }, { header: "Verified sales", width: 1.6, numeric: true },
        { header: "Share", width: 0.8, numeric: true },
      ], [
        ...report.salespersonTotals.map((row) => [row.salesperson, String(row.transactionCount), String(row.units), money(row.totalDiscount), money(row.averageSale), money(row.totalAmount), `${row.percentage.toFixed(1)}%`]),
        ["OVERALL TOTAL", String(total.transactionCount), String(total.units), money(total.totalDiscount), money(total.averageSale), money(total.totalAmount), total.totalAmount ? "100.0%" : "0.0%"],
      ], true);
    }
    table("Branch subtotals", [
      { header: "Branch", width: 4 }, { header: "Transactions", width: 1.3, numeric: true },
      { header: "Units", width: 1, numeric: true }, { header: "Verified sales", width: 2, numeric: true },
      { header: "Share", width: 1, numeric: true },
    ], [
      ...report.branchTotals.map((row) => [row.branch, String(row.transactionCount), String(row.units), money(row.totalAmount), `${row.percentage.toFixed(1)}%`]),
      ["OVERALL TOTAL", String(total.transactionCount), String(total.units), money(total.totalAmount), total.totalAmount ? "100.0%" : "0.0%"],
    ], true);
    const salesByPerson = new Map<string | null, SalesReport["rows"]>();
    if (report.type === "salesperson-sales") for (const row of report.rows) {
      const group = salesByPerson.get(row.salespersonId) ?? [];
      group.push(row);
      salesByPerson.set(row.salespersonId, group);
    }
    const detailGroups = report.type === "salesperson-sales"
      ? report.salespersonTotals.map((group) => ({ heading: `Salesperson: ${group.salesperson} - ${group.transactionCount} receipt(s)`, rows: salesByPerson.get(group.salespersonId) ?? [], subtotal: group }))
      : [{ heading: "Verified sales detail", rows: report.rows, subtotal: null }];
    for (const group of detailGroups) table(group.heading, [
      { header: "Receipt / sold / verified", width: 1.7 }, { header: "Branch", width: 1.25 },
      { header: "Customer / personnel", width: 2.3 }, { header: "Source / payment / status", width: 1.5 },
      { header: "Units", width: 0.6, numeric: true }, { header: "Discount", width: 1.25, numeric: true },
      { header: "Final amount", width: 1.4, numeric: true },
    ], [...group.rows.map((row) => [
      `${row.manualReceiptNumber}\nSold ${dateTime(row.soldAt)}\nVerified ${dateTime(row.verifiedAt)}`, row.branch,
      `Customer: ${row.customer}\nSalesperson: ${row.salesperson}\nEncoder: ${row.encoder}`,
      `${row.source}\n${humanize(row.paymentMethod)}\n${humanize(row.verificationStatus)}`,
      String(row.units), money(row.discountAmount), money(row.totalAmount),
    ]), ...(group.subtotal ? [["SALESPERSON TOTAL", "", "", "", String(group.subtotal.units), money(group.subtotal.totalDiscount), money(group.subtotal.totalAmount)]] : [])], group.subtotal !== null);
  } else if (report.type === "inventory-summary") {
    table("Inventory overview", [{ header: "Measure", width: 3 }, { header: "Total", width: 2, numeric: true }], [
      ["Products in filtered rows", String(report.totals.productCount)], ["Authorized branches in scope", String(report.totals.locationCount)],
      ["Available units", String(report.totals.available)],
    ], true);
    const inventoryColumns: PdfColumn[] = [
      { header: "Item code", width: 1.4 }, { header: "Product", width: 3.5 },
      { header: "Category", width: 1.5 }, { header: "Brand", width: 1.5 }, { header: "Available", width: 1.3, numeric: true },
    ];
    table(report.effectiveScope.length > 1 ? "Product totals across selected branches" : "Available products", inventoryColumns, [
      ...report.rows.map((row) => [row.itemCode, row.product, row.category, row.brand, String(row.available)]),
      ["FULL FILTERED TOTAL", "", "", "", String(report.totals.available)],
    ], true);
    if (report.effectiveScope.length > 1) {
      text("Branch comparison follows in separate sections. Every section includes the full filtered product set, including 0 cells, without narrowing columns for additional branches.");
      for (const location of report.effectiveScope) {
        table(`Branch: ${location.label}`, inventoryColumns, [
          ...report.rows.map((row) => [row.itemCode, row.product, row.category, row.brand, String(row.availableByLocation[location.id])]),
          ["BRANCH TOTAL", "", "", "", String(report.branchTotals.find((total) => total.locationId === location.id)?.available ?? 0)],
        ], true);
      }
    }
  } else if (report.type === "stock-movement") {
    const totals = report.totals;
    text("Sold counts every posted sale in the period, voided sales excluded, so it matches what left the shelf whether or not Accounting has verified the receipt. Cover is how many more periods the available stock lasts at this period's rate.");
    text("Write the shelf count in the Actual column and the difference in Variance. Rows are ordered slowest first.");
    table("Movement overview", [{ header: "Measure", width: 3 }, { header: "Total", width: 2, numeric: true }], [
      ["No movement", String(totals.noMovementCount)], ["Slow moving", String(totals.slowCount)],
      ["Fast moving", String(totals.fastCount)], ["Units sold", String(totals.soldUnits)],
      ["Sales value", money(totals.soldAmount)], ["On hand", String(totals.onHand)],
      ["Available", String(totals.available)], ["Products", String(totals.productCount)],
    ], true);
    table("Stock movement detail", [
      { header: "Item code", width: 1.2 }, { header: "Product", width: 2.6 }, { header: "Branch", width: 1.4 },
      { header: "Movement", width: 1.1 }, { header: "On hand", width: 0.8, numeric: true },
      { header: "Available", width: 0.9, numeric: true }, { header: "Sold", width: 0.7, numeric: true },
      { header: "Cover", width: 0.8, numeric: true }, { header: "Last sold", width: 1.2 },
      { header: "Actual", width: 0.9, numeric: true }, { header: "Variance", width: 0.9, numeric: true },
    ], [
      ...report.rows.map((row) => [
        row.itemCode, row.product, row.branch,
        row.grade === "NO_MOVEMENT" ? "NO MOVEMENT" : row.grade === "SLOW" ? "Slow" : "Fast",
        String(row.onHand), String(row.available), String(row.soldUnits),
        row.coverPeriods === null ? "-" : `${row.coverPeriods.toFixed(1)}x`,
        row.lastSoldAt ? dateTime(row.lastSoldAt) : "Never",
        "", "",
      ]),
      ["OVERALL TOTAL", "", "", "", String(totals.onHand), String(totals.available), String(totals.soldUnits), "", "", "", ""],
    ], true);
  } else {
    const total = report.totals;
    text("Backjob charges are recorded case amounts, not collected payments or additional Sales revenue. Supplier refunds/credits are separate claim tracking, not ledger totals. Amounts follow applied case filters, including status.");
    text("Backjobs list all original items in one case row. Their affected-unit quantity is not recorded; original item selections are not unit counts.");
    table("Case overview", [{ header: "Measure", width: 3 }, { header: "Total", width: 2, numeric: true }], [
      ["Total cases", String(total.total)], ["Open", String(total.open)], ["Completed", String(total.completed)],
      ["Overdue", String(total.overdue)], ["Unresolved quarantined quantity", String(total.unresolvedQuarantinedQuantity)],
      ["Backjob charges recorded (not Sales revenue)", money(total.backjobChargeAmount)],
      ["Supplier refunds (claim tracking, not ledger totals)", money(total.supplierRefundAmount)],
      ["Supplier credits (claim tracking, not ledger totals)", money(total.supplierCreditAmount)],
    ]);
    table("Case breakdowns", [{ header: "Group", width: 1 }, { header: "Value", width: 4 }, { header: "Cases", width: 1, numeric: true }], [
      ...total.byType.map((row) => ["Type", row.label, String(row.count)]),
      ...total.byStatus.map((row) => ["Status", humanize(row.label), String(row.count)]),
      ...total.byBranch.map((row) => ["Branch", row.label, String(row.count)]),
      ...total.byResolution.map((row) => ["Resolution", humanize(row.label), String(row.count)]),
    ]);
    table("Case detail", [
      { header: "Case / references", width: 1.7 }, { header: "Location / party", width: 1.7 },
      { header: "Product / quantity", width: 2.2 }, { header: "Personnel", width: 1.5 },
      { header: "Status / dates", width: 1.8 }, { header: "Case amounts / quarantine", width: 1.8 },
    ], report.rows.map((row) => [
      `${row.recordType}\n${row.reference}\nCase date: ${dateTime(row.caseDate)}\nOriginal: ${row.originalReference || "None"}\nLinked: ${row.linkedCase || "None"}`,
      `${row.branch}\nCustomer / supplier: ${row.party}`,
      `${row.product}\nCase quantity: ${row.quantity === null ? "Not recorded" : row.quantity}`,
      `Assigned: ${row.assignedPersonnel}\nSalesperson: ${row.salesperson}`,
      `${humanize(row.status)}\nResolution: ${humanize(row.resolution)}\nTarget: ${dateTime(row.targetDate)}\nOverdue: ${row.overdue ? "Yes" : "No"}`,
      `Backjob charge recorded: ${row.backjobChargeAmount === null ? "Not applicable" : money(row.backjobChargeAmount)}\nUnresolved quarantine: ${row.unresolvedQuarantinedQuantity}\nSupplier refund: ${money(row.supplierRefundAmount)}\nSupplier credit: ${money(row.supplierCreditAmount)}`,
    ]));
  }

  return finish();
}
