import {
  Bell,
  Boxes,
  ClipboardList,
  LayoutDashboard,
  Package,
  ReceiptText,
  RefreshCw,
  Settings,
  ShoppingCart,
  Users,
  UserCog,
  Wrench,
  LocationEdit,
} from "lucide-react";

export const menus = [
  { label: "Dashboard", href: "/dashboard", icon: LayoutDashboard },
  // { label: "Admin Dashboard", href: "/dashboard2", icon: LayoutDashboard },
  // { label: "Branch Dashboard", href: "/dashboard3", icon: LayoutDashboard },
  { label: "Customers", href: "/customers", icon: Users },
  { label: "Products", href: "/products", icon: Package },
  { label: "Inventory", href: "/inventory", icon: Boxes },
  { label: "Customer Orders", href: "/customer-orders", icon: ClipboardList },
  // { label: "POS / Sales", href: "/pos", icon: ShoppingCart },
  { label: "Job Orders", href: "/job-orders", icon: Wrench },
  { label: "Stock Transfers", href: "/stock-transfers", icon: RefreshCw },
  { label: "Reports", href: "/reports", icon: ReceiptText },
  { label: "Notifications", href: "/notifications", icon: Bell },
  { label: "Branches", href: "/branches", icon: LocationEdit },
  { label: "Users & Roles", href: "/users", icon: UserCog },
  { label: "Settings", href: "/settings", icon: Settings },
] as const;
