ALTER TYPE "InventoryMovementType" ADD VALUE 'SUPPLIER_CLAIM_RETURN';
ALTER TYPE "InventoryMovementType" ADD VALUE 'SUPPLIER_CLAIM_REPAIR_SEND';
ALTER TYPE "InventoryMovementType" ADD VALUE 'SUPPLIER_CLAIM_REPLACEMENT_RECEIPT';
ALTER TYPE "InventoryMovementType" ADD VALUE 'SUPPLIER_CLAIM_REPAIRED_RECEIPT';
ALTER TYPE "InventoryMovementType" ADD VALUE 'SUPPLIER_CLAIM_WRITEOFF';
