"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useRef, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, ArrowLeftRight, Ban, CheckCircle2, Clock, Handshake, PackageCheck, PackagePlus, Printer, Undo2, Wrench, X, type LucideIcon } from "lucide-react";

import { PageShell } from "@/components/page-shell";
import { Badge } from "@/components/ui/badge";
import { Button, buttonVariants } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { warrantyStatusLabels } from "@/lib/contracts/customer-warranties";

type Warranty = { id: string; reference: string; version: number; status: string; resolution: string | null; customerName: string; productId: string | null; productName: string; productItemCode: string; claimQuantity: number; receivedQuantity: number; returnedQuantity: number; concern: string; locationName: string; isLegacy: boolean; legacySaleReference: string | null; legacyReason: string | null; replacementProductName: string | null; intakePhotoName: string | null; replacementProducts: Array<{ id: string; itemCode: string; name: string }>; events: Array<{ id: string; type: string; occurredAt: string; actor: { name: string } }> };
const actions: Record<string, Array<{ action: string; label: string; capability: string; icon: LucideIcon }>> = {
  ASSESSMENT: [{ action: "receive-quarantine", label: "Confirm item received", capability: "customer-warranties:receive-quarantine", icon: PackagePlus }, { action: "return-to-customer", label: "Return unrepaired item", capability: "customer-warranties:release", icon: Undo2 }, { action: "approve-repair", label: "Approve repair", capability: "customer-warranties:approve", icon: Wrench }, { action: "approve-replacement", label: "Approve replacement", capability: "customer-warranties:approve", icon: ArrowLeftRight }, { action: "reject", label: "Reject claim", capability: "customer-warranties:complete", icon: Ban }, { action: "cancel", label: "Cancel claim", capability: "customer-warranties:complete", icon: X }],
  APPROVED_REPAIR: [{ action: "mark-ready", label: "Mark ready for pickup", capability: "customer-warranties:approve", icon: PackageCheck }],
  APPROVED_REPLACEMENT: [{ action: "mark-ready", label: "Mark ready for pickup", capability: "customer-warranties:approve", icon: PackageCheck }, { action: "waiting-stock", label: "Mark waiting for stock", capability: "customer-warranties:approve", icon: Clock }],
  WAITING_STOCK: [{ action: "mark-ready", label: "Mark ready for pickup", capability: "customer-warranties:approve", icon: PackageCheck }], READY: [{ action: "release", label: "Confirm handover to customer", capability: "customer-warranties:release", icon: Handshake }], RELEASED: [{ action: "complete", label: "Complete claim", capability: "customer-warranties:complete", icon: CheckCircle2 }],
};

const actionColors: Record<string, string> = {
  "receive-quarantine": "border-blue-200 bg-blue-600 text-white hover:bg-blue-700",
  "approve-repair": "border-amber-200 bg-amber-500 text-white hover:bg-amber-600",
  "approve-replacement": "border-emerald-200 bg-emerald-600 text-white hover:bg-emerald-700",
  reject: "border-orange-200 bg-orange-500 text-white hover:bg-orange-600",
  cancel: "border-red-200 bg-red-600 text-white hover:bg-red-700",
};

export function WarrantyDetailClient({ capabilities, isOwner }: { capabilities: readonly string[]; isOwner: boolean }) {
  const { warrantyId } = useParams<{ warrantyId: string }>(); const client = useQueryClient();
  const requestKeys = useRef(new Map<string, string>());
  const [notes, setNotes] = useState("");
  const [targetDate, setTargetDate] = useState("");
  const [replacementProductId, setReplacementProductId] = useState("");
  const [replacementReason, setReplacementReason] = useState("");
  const [returnQuantity, setReturnQuantity] = useState("1");
  const [returnReason, setReturnReason] = useState("");
  const query = useQuery({ queryKey: ["customer-warranty", warrantyId], queryFn: async () => { const response = await fetch(`/api/customer-warranties/${warrantyId}`); const json = await response.json(); if (!response.ok) throw new Error(json.error?.message ?? "Unable to load warranty"); return json.data as Warranty; } });
  const mutation = useMutation({ mutationFn: async ({ action, payload = {} }: { action: string; payload?: Record<string, unknown> }) => { const request = { version: query.data!.version, ...payload }; const fingerprint = JSON.stringify({ action, ...request }); let idempotencyKey = requestKeys.current.get(fingerprint); if (!idempotencyKey) { idempotencyKey = crypto.randomUUID(); requestKeys.current.set(fingerprint, idempotencyKey); } const response = await fetch(`/api/customer-warranties/${warrantyId}/${action}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ idempotencyKey, ...request }) }); const json = await response.json(); if (!response.ok) throw new Error(json.error?.message ?? "Unable to update warranty"); requestKeys.current.delete(fingerprint); return json.data as Warranty; }, onSuccess: (data) => { client.setQueryData(["customer-warranty", warrantyId], data); client.invalidateQueries({ queryKey: ["customer-warranties"] }); } });
  const warranty = query.data;
 return <PageShell title={warranty?.reference ?? "Warranty detail"} subtitle="Review the issue, decide on repair or replacement, and track item handovers." actions={<div className="flex flex-wrap gap-2"><Link href="/inventory/returns-warranty/warranties" className={buttonVariants({ variant: "outline" })}><ArrowLeft aria-hidden="true" />Back to warranties</Link>{warranty && capabilities.includes("customer-warranties:print") ? <Link href={`/inventory/returns-warranty/warranties/${warranty.id}/print`} target="_blank" rel="noopener noreferrer" className={buttonVariants({ variant: "outline" })}><Printer aria-hidden="true" />Print</Link> : null}</div>}>
    {query.isLoading ? <p className="text-muted-foreground">Loading warranty...</p> : query.error || !warranty ? <p className="text-destructive">{query.error?.message ?? "Warranty not found"}</p> : <div className="grid gap-5 lg:grid-cols-[2fr_1fr]">
      <div className="space-y-5"><Card><CardHeader className="flex-row flex-wrap items-center justify-between gap-2"><CardTitle>Claim</CardTitle><Badge variant="outline">{warrantyStatusLabels[warranty.status] ?? warranty.status}</Badge></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2"><div><span className="text-sm text-muted-foreground">Customer</span><p>{warranty.customerName}</p></div><div><span className="text-sm text-muted-foreground">Location</span><p>{warranty.locationName}</p></div><div><span className="text-sm text-muted-foreground">Item</span><p>{warranty.claimQuantity} x {warranty.productItemCode} - {warranty.productName}</p></div><div><span className="text-sm text-muted-foreground">Item handovers</span><p>{warranty.receivedQuantity} received · {warranty.returnedQuantity} returned unrepaired</p></div><div><span className="text-sm text-muted-foreground">Resolution</span><p>{warranty.resolution === "REPAIR" ? "Repair" : warranty.resolution === "REPLACEMENT" ? "Replacement" : "Pending assessment"}</p></div>{warranty.isLegacy ? <div className="space-y-1 sm:col-span-2"><p className="text-sm font-medium">Sale not recorded in this system (legacy claim)</p><p className="text-sm text-muted-foreground">The owner entered the customer, product, and warranty period without linking a system sale.</p><p className="text-sm">Original reference: {warranty.legacySaleReference || "Not provided"}</p><p className="text-sm">Reason: {warranty.legacyReason}</p></div> : null}<div className="sm:col-span-2"><span className="text-sm text-muted-foreground">Reported issue</span><p>{warranty.concern}</p></div>{warranty.intakePhotoName ? <a className="break-all text-sm font-medium text-primary underline sm:col-span-2" href={`/api/customer-warranties/${warranty.id}/evidence`} target="_blank" rel="noreferrer">View intake photo ({warranty.intakePhotoName})</a> : <p className="text-sm text-muted-foreground sm:col-span-2">No intake photo attached.</p>}</CardContent></Card>
      <Card><CardHeader><CardTitle>Actions</CardTitle></CardHeader><CardContent className="grid gap-3">
        {warranty.status === "ASSESSMENT" ? <p className="text-sm text-muted-foreground">Confirm receipt only when the customer has handed over the item. Received items are held out of sellable stock (quarantine); approving a repair or replacement does not move stock.</p> : null}
        {warranty.status === "ASSESSMENT" && capabilities.includes("customer-warranties:approve") ? <><div className="grid gap-1.5"><Label htmlFor="targetDate">Target completion date and time</Label><Input id="targetDate" type="datetime-local" value={targetDate} onChange={(event) => setTargetDate(event.target.value)} aria-describedby="target-help" /><p id="target-help" className="text-sm text-muted-foreground">Choose a future date before approving repair or replacement.</p></div><div className="grid gap-1.5"><Label htmlFor="assessmentNotes">Assessment notes</Label><Textarea id="assessmentNotes" value={notes} onChange={(event) => setNotes(event.target.value)} /></div>{isOwner ? <><div className="grid gap-1.5"><Label htmlFor="replacementProductId">Replacement product</Label><select id="replacementProductId" className="h-9 rounded-md border bg-background px-2 text-sm" value={replacementProductId || warranty.productId || ""} onChange={(event) => setReplacementProductId(event.target.value)}>{warranty.replacementProducts.map((product) => <option key={product.id} value={product.id}>{product.itemCode} - {product.name}</option>)}</select></div>{replacementProductId && replacementProductId !== warranty.productId ? <div className="grid gap-1.5"><Label htmlFor="replacementReason">Why use a different replacement product? (required)</Label><Input id="replacementReason" value={replacementReason} onChange={(event) => setReplacementReason(event.target.value)} /></div> : null}</> : null}</> : null}
        {warranty.status === "ASSESSMENT" && warranty.receivedQuantity > warranty.returnedQuantity && capabilities.includes("customer-warranties:release") ? <div className="grid gap-2 rounded-md border p-3"><Label htmlFor="returnQuantity">Unrepaired return quantity</Label><Input id="returnQuantity" type="number" min="1" max={warranty.receivedQuantity - warranty.returnedQuantity} value={returnQuantity} onChange={(event) => setReturnQuantity(event.target.value)} /><Label htmlFor="returnReason">Required return reason</Label><Textarea id="returnReason" value={returnReason} onChange={(event) => setReturnReason(event.target.value)} /></div> : null}
         <div className="flex flex-wrap gap-2">{(actions[warranty.status] ?? []).filter((item) => capabilities.includes(item.capability) && (item.action !== "return-to-customer" || warranty.receivedQuantity > warranty.returnedQuantity)).map((item) => { const approval = item.action === "approve-repair" || item.action === "approve-replacement"; const returning = item.action === "return-to-customer"; const payload = returning ? { quantity: Number(returnQuantity), notes: returnReason } : approval ? { notes: notes || undefined, targetDate: targetDate ? new Date(targetDate).toISOString() : undefined, ...(item.action === "approve-replacement" ? { replacementProductId: replacementProductId || warranty.productId || undefined, replacementReason: replacementReason || undefined } : {}) } : {}; return <Button key={item.action} variant="default" className={actionColors[item.action]} disabled={mutation.isPending || (returning && (!returnReason.trim() || Number(returnQuantity) < 1 || Number(returnQuantity) > warranty.receivedQuantity - warranty.returnedQuantity)) || (approval && (!targetDate || warranty.returnedQuantity > 0)) || (item.action === "approve-replacement" && Boolean(replacementProductId && replacementProductId !== warranty.productId && !replacementReason))} onClick={() => mutation.mutate({ action: item.action, payload })}><item.icon aria-hidden="true" />{item.label}</Button>; })}</div>
        {warranty.receivedQuantity > warranty.returnedQuantity && warranty.status === "ASSESSMENT" ? <p className="text-sm text-muted-foreground">Before rejecting or cancelling, return held items to the customer or record what happened to them through a linked Supplier Claim.</p> : null}{mutation.error ? <p role="alert" className="text-sm text-destructive">{mutation.error.message}</p> : null}{!(actions[warranty.status] ?? []).some((item) => capabilities.includes(item.capability)) ? <p className="text-sm text-muted-foreground">No available actions.</p> : null}
      </CardContent></Card></div>
      <Card><CardHeader><CardTitle>Claim history</CardTitle></CardHeader><CardContent className="space-y-4">{warranty.events.map((event) => <div key={event.id} className="border-l-2 pl-3"><p className="text-sm font-medium">{event.type.replaceAll("_", " ")}</p><p className="text-xs text-muted-foreground">{event.actor.name} · {new Date(event.occurredAt).toLocaleString()}</p></div>)}</CardContent></Card>
    </div>}
  </PageShell>;
}
