import { authorizationErrorResponse, requireCapability } from "@/lib/server/authorization";
import { getReportsSummary } from "../../../lib/server/services/customer-sales";

export async function GET(request: Request) {
  try {
    const actor = await requireCapability(request.headers, "reports:view");
    const summary = await getReportsSummary(actor);
    const format = new URL(request.url).searchParams.get("format");

    if (format === "pdf") {
      const body = [
        "Chezcar Reports",
        `Generated at: ${new Date().toISOString()}`,
        `Generated by: ${actor.userId}`,
        "",
        `Sales total: ${summary.sales.totalSales}`,
        `Transactions: ${summary.sales.transactionCount}`,
        `Accounting unverified: ${summary.accounting.unverified}`,
        `Accounting verified: ${summary.accounting.verified}`,
        `Accounting flagged: ${summary.accounting.flagged}`,
        `Open orders: ${summary.orders.open}`,
        `Inventory rows: ${summary.inventory.length}`,
      ].join("\n");

      return new Response(body, {
        headers: {
          "Content-Type": "application/pdf",
          "Content-Disposition": "attachment; filename=chezcar-report.pdf",
        },
      });
    }

    return Response.json({ data: summary });
  } catch (error) {
    return authorizationErrorResponse(error);
  }
}
